version: "3.3"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - AT_SECRET=${AT_SECRET}
            - RT_SECRET=${RT_SECRET}
        ports:
            - "3000:3000"
