export enum UserRole {
  ADMIN = 'ADMIN',
  REVENUEMANAGER = 'REVENUEMANAGER',
  CLUSTERMANAGER = 'CLUSTERMANAGER',
  SHIFTMANAGER = 'SHIFTMANAGER',
  FRANCHISEOWNER = 'FRANCHISEOWNER',
  CONSUMER = 'CONSUMER',
  WAREHOUSEADMIN = 'WAREHOUSEADMIN',
}
