export enum UserRole {
  VISITOR = 'VISITOR',
  ADMIN = 'ADMIN',
  REVENUEMANAGER = 'REVENUEMANAGER',
  CLUSTERMANAGER = 'CLUSTERMANAGER',
  SHIFTMANAGER = 'SHIFTMANAGER',
  FRANCHISEOWNER = 'FRANCHISEOWNER',
  CONSUMER = 'CONSUMER',
  WAREHOUSEADMIN = 'WAREHOUSEADMIN',
  INTERNAL = 'INTERNAL',
  INTEGRATION = 'INTEGRATION',
}
