-- AlterTable
ALTER TABLE "devices" ALTER COLUMN "user_id" DROP NOT NULL,
ALTER COLUMN "mac_address" DROP NOT NULL,
ALTER COLUMN "manufacturer" DROP NOT NULL,
ALTER COLUMN "model" DROP NOT NULL,
ALTER COLUMN "os" DROP NOT NULL,
ALTER COLUMN "app_version" DROP NOT NULL,
ALTER COLUMN "notification_token" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL,
ALTER COLUMN "upadted_by" DROP NOT NULL;

-- AlterTable
ALTER TABLE "otp_tokens" ALTER COLUMN "otp" DROP NOT NULL,
ALTER COLUMN "user_id" DROP NOT NULL,
ALTER COLUMN "phone_number" DROP NOT NULL,
ALTER COLUMN "valid_till" DROP NOT NULL,
ALTER COLUMN "sent_at" DROP NOT NULL,
ALTER COLUMN "retries" DROP NOT NULL,
ALTER COLUMN "retries_allowed" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL,
ALTER COLUMN "upadted_by" DROP NOT NULL;

-- AlterTable
ALTER TABLE "refresh_token" ALTER COLUMN "valid_till" DROP NOT NULL,
ALTER COLUMN "revoked" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "updated_at" DROP NOT NULL,
ALTER COLUMN "upadted_by" DROP NOT NULL;
